version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    networks:
      - webnet

  backend:
    build: ./backend
    networks:
      - webnet

networks:
  webnet:
