version: '3.8'

services:
  frontend:
    image: yemregundogmus/ds-frontend:latest
    ports:
      - "8501:8501"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  backend:
    image: yemregundogmus/ds-backend:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: overlay